### ISSUE TITLE
Question: Entity documents

### ISSUE THREAD

**Issue by StuartIanNaylor** [fractalego/wafl#63]
If you presented yaml entity documents to walf with say something like langchain could waffle create control yaml from input?

If you take the MQTT of common opensource devices such as https://tasmota.github.io/docs/Commands/#control or https://esphome.io/components/light/

I guess all entities and controls of how they have been named could be exported as documents so that a LLM would get [zone] turn the light on

Likely in the documents the Yaml representation of that entity would exist
[zone:lounge
    entity:light
    name:main light
    state:on/off
    control:on/off]
 ]
 
 Its just a general question and ignore if I got the control yaml totally wrong as just an example but I have been wondering if say some of the smaller 7b parameter models such as llama with llama.cpp could be finetuned and if you could provide formatted yaml documents could you train a system to output code as the only entities outside of the LLM's knowledge is the naming those items have.
 So if those entities where presented as documents could a LLM return the correct formated yaml?
 
 If it did then you have just solved home-assistants and control wih the like of homeassistant or openhab.

**Comment by fractalego** [comment]
Hi Stuart, I believe the answer is "yes", there could (and should) be yaml for control. I am in the process of rewriting some of the code, and fine-tuning a 7B llm for this task. It should be ready by the end of November and I am going to ping you when it is ready.

**Comment by StuartIanNaylor** [comment]
Cool there is a great KWS https://github.com/dscripka/openWakeWord that use synthetics to train and is super easy.
Wenet deliberately go back to n-gram LM type moels of ASR to make command sentence detection more accurate.
https://wenet.org.cn/wenet/lm.html
https://wenet.org.cn/wenet/context.html

LLama & Waf feeding openhab would be exceptionally cool :)
